In [1]:
import pandas as pd

import numpy as np

import matplotlib

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

from collections import Counter

In [2]:
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)
pd.set_option('display.width', 5000)

In [4]:
pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
from sklearn import datasets

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

import sklearn.metrics as metrics

from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

from sklearn.metrics import precision_score

from sklearn.metrics import f1_score

from sklearn.metrics import recall_score



from sklearn.tree import export_graphviz

In [7]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import make_classification

from sklearn.ensemble import BaggingClassifier

from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import GradientBoostingClassifier

In [8]:
filepath0 = "main_88000.csv"

In [9]:
data0 = pd.read_csv(filepath0)
frame = data0

In [10]:
X = frame.drop([" Label"],axis=1)
Y = frame[" Label"]

In [11]:
counter = Counter(Y)

for a, b in counter.items():
  dist = b/len(Y) * 100
  # print (f"Label={a},\t\t\t\t n={b} ({dist}%)")
  print (f"n={b} ({dist:.3f}%), \t Label={a}")

n=30000 (34.091%), 	 Label=BENIGN
n=19500 (22.159%), 	 Label=DDoS/Dos
n=15000 (17.045%), 	 Label=PortScan
n=8000 (9.091%), 	 Label=Brute Force
n=4000 (4.545%), 	 Label=Bot
n=7500 (8.523%), 	 Label=Web Attacks
n=4000 (4.545%), 	 Label=Infiltration


In [12]:
scaler = StandardScaler()

In [13]:
columns = X.columns

In [14]:
X_std = scaler.fit_transform(X)

In [15]:
X_std = pd.DataFrame(X_std, columns = columns)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_std, Y, test_size=0.3, random_state=101)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((61600, 36), (26400, 36), (61600,), (26400,))

In [18]:
rf = RandomForestClassifier(max_depth=5, random_state=0)
# 6

In [19]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=0)

In [20]:
rf_predictions = rf.predict(X_test)

In [21]:
rf_predictions

array(['Brute Force', 'BENIGN', 'PortScan', ..., 'BENIGN', 'DDoS/Dos',
       'PortScan'], dtype=object)

In [22]:
print(confusion_matrix(y_test, rf_predictions))

[[8994    0    0    0    0    0    0]
 [   0 1242    0    0    0    0    1]
 [   0    0 2406    0    0    0    0]
 [   1    1    0 5905    0    0    0]
 [   0    0    0    0 1167    0    0]
 [   0    0    0   17    0 4442    0]
 [   0    0    0    5    0    0 2219]]


In [23]:
print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00      8994
         Bot       1.00      1.00      1.00      1243
 Brute Force       1.00      1.00      1.00      2406
    DDoS/Dos       1.00      1.00      1.00      5907
Infiltration       1.00      1.00      1.00      1167
    PortScan       1.00      1.00      1.00      4459
 Web Attacks       1.00      1.00      1.00      2224

    accuracy                           1.00     26400
   macro avg       1.00      1.00      1.00     26400
weighted avg       1.00      1.00      1.00     26400



In [24]:
rf.score(X_test, y_test)

0.9990530303030303

In [25]:
boostin = AdaBoostClassifier(RandomForestClassifier(), n_estimators=5, learning_rate = 1)
# boostin = GradientBoostingClassifier(RandomForestClassifier(), n_estimators=5 )
boostin.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=5)

In [26]:
boostin.score(X_test, y_test)

0.9998484848484849

In [27]:
boostin_predictions = boostin.predict(X_test)
print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00      8994
         Bot       1.00      1.00      1.00      1243
 Brute Force       1.00      1.00      1.00      2406
    DDoS/Dos       1.00      1.00      1.00      5907
Infiltration       1.00      1.00      1.00      1167
    PortScan       1.00      1.00      1.00      4459
 Web Attacks       1.00      1.00      1.00      2224

    accuracy                           1.00     26400
   macro avg       1.00      1.00      1.00     26400
weighted avg       1.00      1.00      1.00     26400

